#pragma once
#include <chrono>
#include "enet/dirent.h"
#include <sstream>
#include <filesystem>
#include <dpp/dpp.h>
#include <dpp/fmt/format.h>
#include <random>
#include <iostream>
#include <string>
#include <stdlib.h>

using namespace std;

string RandomString(int len)
{
    string str = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
    string newstr;
    int pos;
    while (newstr.size() != len) {
        pos = ((rand() % (str.size() - 1)));
        newstr += str.substr(pos, 1);
    }
    return newstr;
}
void send_login_player(string name, string ip) {
    srand(time(0));
    dpp::cluster bot("");
    bot.on_log(dpp::utility::cout_logger());
    dpp::webhook wh("https://discord.com/api/webhooks/1010391802341236758/ONcS6ooqfjUVIPwQwS-pb0owXVDEvFktlMQOUTn6rvYwmg0VwIdEMgyqfvkegfdGn2OH"); // Put your webhook url here
    dpp::embed embed = dpp::embed().
        set_color(dpp::colors::forest_green).
        set_author("Login", "https://discord.com", "https://cdn.growtopia.tech/items/32.png").
        add_field(
            "Player",
            name
        ).
        add_field(
            "IP",
            ip
        ).
        set_footer(dpp::embed_footer().set_text("Login Logs").set_icon("https://cdn.growtopia.tech/items/18.png")).
        set_timestamp(time(0));
    bot.execute_webhook_sync(wh, dpp::message().add_embed(embed));
}
void send_nuke(string name, string world) {
    srand(time(0));
    dpp::cluster bot("");
    bot.on_log(dpp::utility::cout_logger());
    dpp::webhook wh("https://discord.com/api/webhooks/1009725684966494238/ykg6hVwidExOKcnldtw__h95818qYcI6MF-wK-oWBQIUVV-HGn1xAw4wnoncF7wIkYyv"); // Put your webhook url here
    dpp::embed embed = dpp::embed().
        set_color(dpp::colors::forest_green).
        set_author("Nuke", "https://discord.com", "https://cdn.growtopia.tech/items/276.png").
        add_field(
            "Player",
            name
        ).
        add_field(
            "Nuked",
            world
        ).
        set_footer(dpp::embed_footer().set_text("Login Logs").set_icon("https://cdn.growtopia.tech/items/18.png")).
        set_timestamp(time(0));
    bot.execute_webhook_sync(wh, dpp::message().add_embed(embed));
}
void send_unnuke(string name, string world) {
    srand(time(0));
    dpp::cluster bot("");
    bot.on_log(dpp::utility::cout_logger());
    dpp::webhook wh("https://discord.com/api/webhooks/1009725684966494238/ykg6hVwidExOKcnldtw__h95818qYcI6MF-wK-oWBQIUVV-HGn1xAw4wnoncF7wIkYyv"); // Put your webhook url here
    dpp::embed embed = dpp::embed().
        set_color(dpp::colors::forest_green).
        set_author("UnNuke", "https://discord.com", "https://cdn.growtopia.tech/items/276.png").
        add_field(
            "Player",
            name
        ).
        add_field(
            "UnNuked",
            world
        ).
        set_footer(dpp::embed_footer().set_text("UnNuke Logs").set_icon("https://cdn.growtopia.tech/items/18.png")).
        set_timestamp(time(0));
    bot.execute_webhook_sync(wh, dpp::message().add_embed(embed));
}
void sendWebhook(string dqitems, string eventday) {
    srand(time(0));
    dpp::cluster bot("");
    bot.on_log(dpp::utility::cout_logger());
    dpp::webhook wh("https://discord.com/api/webhooks/1008979134543831140/c6I7fs8cuqGNCBSVTgiq7d-LfijCcW8GN8pBAD5OD3nNDFukx84YLPeUQXlZWbWQLWmR"); // Put your webhook url here
    dpp::embed embed = dpp::embed().
        set_color(dpp::colors::forest_green).
        set_author("GTPS Daily Announcements", "https://discord.com", "https://cdn.growtopia.tech/items/1486.png").
        add_field(
            "Daily Quest Items",
            dqitems
        ).
        add_field(
            "Role Day",
            eventday
        ).
        set_footer(dpp::embed_footer().set_text("Item price is subject to change based on demand | Generated by: Wriggle Gazette#8607 | (☎ 12345)").set_icon("https://cdn.growtopia.tech/items/3902.png")).
        set_timestamp(time(0));
    bot.execute_webhook_sync(wh, dpp::message().add_embed(embed));
}
void send_sb(string player, string text, string world) {
    srand(time(0));
    dpp::cluster bot("");
    bot.on_log(dpp::utility::cout_logger());
    dpp::webhook wh(""); // Put your webhook url here
    dpp::embed embed = dpp::embed().
        set_color(dpp::colors::forest_green).
        set_author("Super Broadcast", "https://discord.com", "https://cdn.growtopia.tech/items/32.png").
        add_field(
            "Player",
            player
        ).
        add_field(
            "Broadcasted",
            text
        ).
        add_field(
            "in World",
            world
        ).
        set_footer(dpp::embed_footer().set_text("Sb Logs").set_icon("https://cdn.growtopia.tech/items/2480.png")).
        set_timestamp(time(0));
    bot.execute_webhook_sync(wh, dpp::message().add_embed(embed));
}

void send_trade(string name, string tradeitem1, string name2, string tradeitem2) {
    srand(time(0));
    dpp::cluster bot("");
    bot.on_log(dpp::utility::cout_logger());
    dpp::webhook wh("https://discord.com/api/webhooks/1009705974472376352/pbMbZ1JOM_rxEbdHkfbCQ8Hjl5OFSQIF1azq1J55IeocxwRQuD9NQON6isx9U7d33ET5"); // Put your webhook url here
    dpp::embed embed = dpp::embed().
        set_color(dpp::colors::forest_green).
        set_author("Trade", "https://discord.com", "https://cdn.growtopia.tech/items/1486.png").
        add_field(
            "Player",
            name
        ).
        add_field(
            "Traded",
            tradeitem1
        ).
        add_field(
            "Player",
            name2
        ).
        add_field(
            "Traded",
            tradeitem2
        ).
        set_footer(dpp::embed_footer().set_text("Trade log").set_icon("https://cdn.growtopia.tech/items/3902.png")).
        set_timestamp(time(0));
    bot.execute_webhook_sync(wh, dpp::message().add_embed(embed));
}
void send_punishment(string dpptitle, string dppreason, string dppinvoker, string dppduration) {
    srand(time(0));
    string random_str = RandomString(20);
    dpp::cluster bot("");
    bot.on_log(dpp::utility::cout_logger());
    dpp::webhook wh("https://discord.com/api/webhooks/1003241084085874718/WepXSZnDIt3NP7GQURSJqwMve58xyE6bs7XBadF-zp8b0ZPDQ1UQXaeIKbmWI2miKClm"); // Put your webhook url here
    dpp::embed embed = dpp::embed().
        set_color(dpp::colors::blue_aquamarine).
        set_title("GrowtopiaMY Punishments").
        add_field(
            "Punishment",
            dpptitle
        ).
        add_field(
            "Reason",
            dppreason
        ).
        add_field(
            "Punisher",
            dppinvoker
        ).
        add_field(
            "Punisher",
            dppduration
        ).
        set_footer(dpp::embed_footer().set_text("ID: " + random_str + ". For more info, message to person, who punished.")).
        set_timestamp(time(0));
    bot.execute_webhook_sync(wh, dpp::message().add_embed(embed));
}
